# Generated by Django 4.2.4 on 2023-08-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='loan_request',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='request',
            name='borrower',
        ),
        migrations.DeleteModel(
            name='Funding',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
